### ISSUE TITLE
How do you yum install against uploaded RPMs?

### ISSUE THREAD

**Issue by JonKohler** [FINRAOS/yum-nginx-api#14]
My apologies if this is a silly question, but I can't figure this out. I've set this up and have successfully posted RPMs to this service, with /api/upload working perfectly as expected.

I can see the images under /api/repo just fine, returned in JSON format, but it's occurring to me that I can't figure out how to pull RPMs out from there.

I've tried to walk the source code, and it looks like the only API route exposed for /api/repo is configured to only return a JSON. 

I don't see any code/handlers to actually pass back the RPMs or expose a xml based resource that yum might understand.

I checked the wiki, commit history, pull request history, and google-fu'd heavily. I also watched the only video I could find on this (https://www.youtube.com/watch?v=xVRBDK6s7Og&feature=youtu.be) and it was alluded to but I couldn't see any code to actually do this.

The meetup page (https://www.meetup.com/DC-continuous-delivery/events/219648907/) which links to some slides (http://marshyski.com/talks/rpm-build-api-ci.html) but that URL does not resolve.

**Comment by marshyski** [comment]
Hi @JonKohler, thank you for your interest in yum-nginx-api! NGINX is used to serve the RPMs for yum/rpm. You can use this configuration and hit this route, https://github.com/FINRAOS/yum-nginx-api/blob/master/nginx/nginx.conf#L54

NGINX is a dependency, but since a lot of organizations support it, it's easiest to get buy-in, but I would love to remove NGINX and serve right from the Go web service. Is this something you are interested in? I can propose a changeset for you to review along with @kood1 if it simplifies your architecture.

**Comment by JonKohler** [comment]
I'm all for simplification if you're up for proposing something.

In the meantime, are you saying that with NGINX, one should just be able to point yum.conf like this? or am I misinterpreting thing?

```
[base]
name=yum-api-repo
enabled=1
baseurl=http://ngnix-here/repo
gpgcheck=0
priority=1
```

**Comment by marshyski** [comment]
@JonKohler that looks correct, is it not working? I can generate some configurations and Dockerfiles for references. It is time I update the project dependencies.

The proposed change is to serve the static content (RPM) through the go web services at a route such as `/yum`  I'd like to put together a design document and share it with you since I run into this in multiple environments between debs and RPMs.

**Comment by marshyski** [comment]
@JonKohler @kood1 this is my proposal to support additional functionality in yum-nginx-api and the removal of NGINX with the go web server already being built.

https://gist.github.com/marshyski/f1d69ce007a3080139d9ea8b38477a26

**Comment by marshyski** [comment]
Hey @JonKohler still interested in helping out?

**Comment by marshyski** [comment]
@JonKohler  just cut an updated release, keeping this issue open if anyone is interested in the proposed changes.

**Comment by JonKohler** [comment]
Hey @marshyski - sorry I dropped off the face of the earth, back half of the year was chocked full of shenanigans and I haven't gotten around to drilling back into this project. I think at a larger level, the rest of the engineering org is just moving things left and right to artifactory though :/

**Comment by marshyski** [comment]
@JonKohler makes sense, especially for a larger org. Thank you for trying out yum-nginx-api!
